name:                xmonad-exe
version:             0.1.0.0
github:              "githubuser/xmonad"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

description:         Please see the README on GitHub at <https://github.com/githubuser/xmonad#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  xmonad-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers
    - process
    - xmonad
    - xmonad-contrib
